local Helpers = require("avante.history.helpers")
local Line = require("avante.ui.line")
local Utils = require("avante.utils")
local Highlights = require("avante.highlights")

local M = {}

---@diagnostic disable-next-line: deprecated
local islist = vim.islist or vim.tbl_islist

---Converts text into format suitable for UI
---@param text string
---@param decoration string | nil
---@param filter? fun(text_line: string, idx: integer, len: integer): boolean
---@return avante.ui.Line[]
local function text_to_lines(text, decoration, filter)
  local text_lines = vim.split(text, "\n")
  local lines = {}
  for idx, text_line in ipairs(text_lines) do
    if filter and not filter(text_line, idx, #text_lines) then goto continue end
    if decoration then
      table.insert(lines, Line:new({ { decoration }, { text_line } }))
    else
      table.insert(lines, Line:new({ { text_line } }))
    end
    ::continue::
  end
  return lines
end

---Converts text into format suitable for UI
---@param text string
---@param decoration string | nil
---@param truncate boolean | nil
---@return avante.ui.Line[]
local function text_to_truncated_lines(text, decoration, truncate)
  local text_lines = vim.split(text, "\n")
  local lines = {}
  for _, text_line in ipairs(text_lines) do
    if truncate and #lines > 3 then
      table.insert(
        lines,
        Line:new({
          { decoration },
          {
            string.format("... (Result truncated, remaining %d lines not shown)", #text_lines - #lines + 1),
            Highlights.AVANTE_COMMENT_FG,
          },
        })
      )
      break
    end
    table.insert(lines, Line:new({ { decoration }, { text_line } }))
  end
  return lines
end

---@param lines avante.ui.Line[]
---@param decoration string | nil
---@param truncate boolean | nil
---@return avante.ui.Line[]
local function lines_to_truncated_lines(lines, decoration, truncate)
  local truncated_lines = {}
  for idx, line in ipairs(lines) do
    if truncate and #truncated_lines > 3 then
      table.insert(
        truncated_lines,
        Line:new({
          { decoration },
          {
            string.format("... (Result truncated, remaining %d lines not shown)", #lines - idx + 1),
            Highlights.AVANTE_COMMENT_FG,
          },
        })
      )
      break
    end
    table.insert(truncated_lines, line)
  end
  return truncated_lines
end

---Converts "thinking" item into format suitable for UI
---@param item AvanteLLMMessageContentItem
---@return avante.ui.Line[]
local function thinking_to_lines(item)
  local text = item.thinking or item.data or ""
  local text_lines = vim.split(text, "\n")
  --- trim prefix empty lines
  while #text_lines > 0 and text_lines[1] == "" do
    table.remove(text_lines, 1)
  end
  --- trim suffix empty lines
  while #text_lines > 0 and text_lines[#text_lines] == "" do
    table.remove(text_lines, #text_lines)
  end
  local ui_lines = {}
  table.insert(ui_lines, Line:new({ { Utils.icon("🤔 ") .. "Thought content:" } }))
  table.insert(ui_lines, Line:new({ { "" } }))
  for _, text_line in ipairs(text_lines) do
    table.insert(ui_lines, Line:new({ { "> " .. text_line } }))
  end
  return ui_lines
end

---Converts logs generated by a tool during execution into format suitable for UI
---@param tool_name string
---@param logs string[]
---@return avante.ui.Line[]
function M.tool_logs_to_lines(tool_name, logs)
  local ui_lines = {}
  local num_logs = #logs

  for log_idx = 1, num_logs do
    local log_lines = vim.split(logs[log_idx]:gsub("^%[" .. tool_name .. "%]: ", "", 1), "\n")
    local num_lines = #log_lines

    for line_idx = 1, num_lines do
      local decoration = "│  "
      table.insert(ui_lines, Line:new({ { decoration }, { " " .. log_lines[line_idx] } }))
    end
  end
  return ui_lines
end

local STATE_TO_HL = {
  generating = "AvanteStateSpinnerToolCalling",
  failed = "AvanteStateSpinnerFailed",
  succeeded = "AvanteStateSpinnerSucceeded",
}

function M.get_diff_lines(old_str, new_str, decoration, truncate)
  local lines = {}
  local line_count = 0
  local old_lines = vim.split(old_str, "\n")
  local new_lines = vim.split(new_str, "\n")
  ---@diagnostic disable-next-line: assign-type-mismatch, missing-fields
  local patch = vim.diff(old_str, new_str, { ---@type integer[][]
    algorithm = "histogram",
    result_type = "indices",
    ctxlen = vim.o.scrolloff,
  })
  local prev_start_a = 0
  local truncated_lines = 0
  for _, hunk in ipairs(patch) do
    local start_a, count_a, start_b, count_b = unpack(hunk)
    local no_change_lines = vim.list_slice(old_lines, prev_start_a, start_a - 1)
    if truncate then
      local last_three_no_change_lines = vim.list_slice(no_change_lines, #no_change_lines - 3)
      truncated_lines = truncated_lines + #no_change_lines - #last_three_no_change_lines
      if #no_change_lines > 4 then
        table.insert(lines, Line:new({ { decoration }, { "...", Highlights.AVANTE_COMMENT_FG } }))
      end
      no_change_lines = last_three_no_change_lines
    end
    for idx, line in ipairs(no_change_lines) do
      if truncate and line_count > 10 then
        truncated_lines = truncated_lines + #no_change_lines - idx
        break
      end
      line_count = line_count + 1
      table.insert(lines, Line:new({ { decoration }, { line } }))
    end
    prev_start_a = start_a + count_a
    if count_a > 0 then
      local delete_lines = vim.list_slice(old_lines, start_a, start_a + count_a - 1)
      for idx, line in ipairs(delete_lines) do
        if truncate and line_count > 10 then
          truncated_lines = truncated_lines + #delete_lines - idx
          break
        end
        line_count = line_count + 1
        table.insert(lines, Line:new({ { decoration }, { line, Highlights.TO_BE_DELETED_WITHOUT_STRIKETHROUGH } }))
      end
    end
    if count_b > 0 then
      local create_lines = vim.list_slice(new_lines, start_b, start_b + count_b - 1)
      for idx, line in ipairs(create_lines) do
        if truncate and line_count > 10 then
          truncated_lines = truncated_lines + #create_lines - idx
          break
        end
        line_count = line_count + 1
        table.insert(lines, Line:new({ { decoration }, { line, Highlights.INCOMING } }))
      end
    end
  end
  if prev_start_a < #old_lines then
    -- Append remaining old_lines
    local no_change_lines = vim.list_slice(old_lines, prev_start_a, #old_lines)
    local first_three_no_change_lines = vim.list_slice(no_change_lines, 1, 3)
    for idx, line in ipairs(first_three_no_change_lines) do
      if truncate and line_count > 10 then
        truncated_lines = truncated_lines + #first_three_no_change_lines - idx
        break
      end
      line_count = line_count + 1
      table.insert(lines, Line:new({ { decoration }, { line } }))
    end
  end
  if truncate and truncated_lines > 0 then
    table.insert(
      lines,
      Line:new({
        { decoration },
        {
          string.format("... (Result truncated, remaining %d lines not shown)", truncated_lines),
          Highlights.AVANTE_COMMENT_FG,
        },
      })
    )
  end
  return lines
end

---Render the collected output of an ACP terminal (see acp_client terminals)
---@param snapshot { output: string, truncated: boolean, exitStatus: avante.acp.TerminalExitStatus|nil } | nil
---@param decoration string | nil
---@param truncate boolean | nil
---@return avante.ui.Line[]
function M.get_terminal_lines(snapshot, decoration, truncate)
  local lines = {}
  if not snapshot then
    table.insert(lines, Line:new({ { decoration }, { "...", Highlights.AVANTE_COMMENT_FG } }))
    return lines
  end
  local output = snapshot.output or ""
  output = output:gsub("\r\n", "\n"):gsub("\n+$", "")
  if output ~= "" then
    local text_lines = vim.split(output, "\n")
    local max_lines = 4
    local start_idx = 1
    if truncate and #text_lines > max_lines then
      start_idx = #text_lines - max_lines + 1
      table.insert(
        lines,
        Line:new({
          { decoration },
          {
            string.format("... (Output truncated, earlier %d lines not shown)", start_idx - 1),
            Highlights.AVANTE_COMMENT_FG,
          },
        })
      )
    elseif snapshot.truncated then
      table.insert(
        lines,
        Line:new({ { decoration }, { "... (earlier output dropped by byte limit)", Highlights.AVANTE_COMMENT_FG } })
      )
    end
    for idx = start_idx, #text_lines do
      table.insert(lines, Line:new({ { decoration }, { text_lines[idx] } }))
    end
  end
  local exit_status = snapshot.exitStatus
  if exit_status then
    local exit_code = exit_status.exitCode
    if exit_code == vim.NIL then exit_code = nil end
    local signal = exit_status.signal
    if signal == vim.NIL then signal = nil end
    local status_text
    if signal then
      status_text = "terminated by " .. tostring(signal)
    else
      status_text = "exit code: " .. tostring(exit_code or 0)
    end
    local hl = (exit_code == 0 and not signal) and Highlights.AVANTE_COMMENT_FG or Highlights.AVANTE_TASK_FAILED
    table.insert(lines, Line:new({ { decoration }, { status_text, hl } }))
  else
    table.insert(lines, Line:new({ { decoration }, { "running...", Highlights.AVANTE_COMMENT_FG } }))
  end
  return lines
end

---@param content any
---@param decoration string | nil
---@param truncate boolean | nil
---@param terminals table<string, table> | nil Terminal snapshots keyed by terminalId (for `terminal` content)
function M.get_content_lines(content, decoration, truncate, terminals)
  local lines = {}
  local content_obj = content
  if type(content) == "string" then
    local ok, content_obj_ = pcall(vim.json.decode, content)
    if ok then content_obj = content_obj_ end
  end
  if type(content_obj) == "table" then
    if islist(content_obj) then
      local all_lines = {}
      for _, content_item in ipairs(content_obj) do
        if type(content_item) == "string" then
          local lines_ = text_to_lines(content_item, decoration)
          all_lines = vim.list_extend(all_lines, lines_)
        end
      end
      local lines_ = lines_to_truncated_lines(all_lines, decoration, truncate)
      lines = vim.list_extend(lines, lines_)
    end
    if type(content_obj.content) == "string" then
      local lines_ = text_to_truncated_lines(content_obj.content, decoration, truncate)
      lines = vim.list_extend(lines, lines_)
    end
    if islist(content_obj.content) then
      local all_lines = {}
      for _, content_item in ipairs(content_obj.content) do
        if type(content_item) == "string" then
          local lines_ = text_to_lines(content_item, decoration)
          all_lines = vim.list_extend(all_lines, lines_)
        end
      end
      local lines_ = lines_to_truncated_lines(all_lines, decoration, truncate)
      lines = vim.list_extend(lines, lines_)
    end
    if islist(content_obj.matches) then
      local all_lines = {}
      for _, content_item in ipairs(content_obj.matches) do
        if type(content_item) == "string" then
          local lines_ = text_to_lines(content_item, decoration)
          all_lines = vim.list_extend(all_lines, lines_)
        end
      end
      local lines_ = lines_to_truncated_lines(all_lines, decoration, truncate)
      lines = vim.list_extend(lines, lines_)
    end
  end
  if type(content_obj) == "string" then
    local lines_ = text_to_lines(content_obj, decoration)
    local line_count = 0
    for idx, line in ipairs(lines_) do
      if truncate and line_count > 3 then
        table.insert(
          lines,
          Line:new({
            { decoration },
            {
              string.format("... (Result truncated, remaining %d lines not shown)", #lines_ - idx + 1),
              Highlights.AVANTE_COMMENT_FG,
            },
          })
        )
        break
      end
      line_count = line_count + 1
      table.insert(lines, line)
    end
  end
  if type(content_obj) == "number" then
    table.insert(lines, Line:new({ { decoration }, { tostring(content_obj) } }))
  end
  if islist(content) then
    for _, content_item in ipairs(content) do
      local line_count = 0
      if content_item.type == "content" then
        if content_item.content.type == "text" then
          local lines_ = text_to_lines(content_item.content.text, decoration, function(text_line, idx, len)
            if idx == 1 and text_line:match("^%s*```%s*$") then return false end
            if idx == len and text_line:match("^%s*```%s*$") then return false end
            return true
          end)
          for idx, line in ipairs(lines_) do
            if truncate and line_count > 3 then
              table.insert(
                lines,
                Line:new({
                  { decoration },
                  {
                    string.format("... (Result truncated, remaining %d lines not shown)", #lines_ - idx + 1),
                    Highlights.AVANTE_COMMENT_FG,
                  },
                })
              )
              break
            end
            line_count = line_count + 1
            table.insert(lines, line)
          end
        end
      elseif
        content_item.type == "diff"
        and content_item.oldText ~= nil
        and content_item.newText ~= nil
        and content_item.oldText ~= vim.NIL
        and content_item.newText ~= vim.NIL
      then
        local relative_path = Utils.relative_path(content_item.path)
        table.insert(lines, Line:new({ { decoration }, { "Path: " .. relative_path } }))
        local lines_ = M.get_diff_lines(content_item.oldText, content_item.newText, decoration, truncate)
        lines = vim.list_extend(lines, lines_)
      elseif content_item.type == "terminal" and content_item.terminalId then
        local snapshot = terminals and terminals[content_item.terminalId] or nil
        local lines_ = M.get_terminal_lines(snapshot, decoration, truncate)
        lines = vim.list_extend(lines, lines_)
      end
    end
  end
  return lines
end

--- Claude Code tool names (from `_meta.claudeCode.toolName`) that spawn a subagent.
local SUBAGENT_TOOL_NAMES = { Task = true, Agent = true }

---Whether this message is an ACP tool call that spawned a subagent
---(Claude Code `Task`/`Agent`). Falls back to a "think" tool call that has
---received nested child updates.
---@param message avante.HistoryMessage
---@return boolean
function M.is_subagent_tool_call(message)
  if SUBAGENT_TOOL_NAMES[message.acp_tool_name or ""] then return true end
  local call = message.acp_tool_call
  return call ~= nil and call.kind == "think" and message.acp_children ~= nil and #message.acp_children > 0
end

---Whether this message is an ACP tool call presenting a plan for approval
---(Claude Code `ExitPlanMode`, ACP kind "switch_mode").
---@param message avante.HistoryMessage
---@return boolean
function M.is_plan_tool_call(message)
  if message.acp_tool_name == "ExitPlanMode" then return true end
  local call = message.acp_tool_call
  return call ~= nil and call.kind == "switch_mode"
end

---Extracts the first text block from ACP tool call content, if any.
---@param content ACPToolCallContent[] | nil
---@return string | nil
function M.get_first_text_content(content)
  if type(content) ~= "table" or not islist(content) then return nil end
  for _, item in ipairs(content) do
    if
      type(item) == "table"
      and item.type == "content"
      and type(item.content) == "table"
      and item.content.type == "text"
      and type(item.content.text) == "string"
    then
      return item.content.text
    end
  end
  return nil
end

---Returns the plan markdown for a plan tool call.
---@param message avante.HistoryMessage
---@return string | nil
function M.get_plan_text(message)
  if type(message.acp_plan) == "string" then return message.acp_plan end
  local call = message.acp_tool_call
  if not call then return nil end
  if type(call.rawInput) == "table" and type(call.rawInput.plan) == "string" then return call.rawInput.plan end
  return M.get_first_text_content(call.content)
end

---Returns the prompt given to a subagent.
---@param message avante.HistoryMessage
---@return string | nil
function M.get_subagent_prompt(message)
  if type(message.acp_subagent_prompt) == "string" then return message.acp_subagent_prompt end
  local call = message.acp_tool_call
  if not call then return nil end
  if type(call.rawInput) == "table" and type(call.rawInput.prompt) == "string" then return call.rawInput.prompt end
  return nil
end

local CHILD_STATUS_ICON = {
  pending = "…",
  in_progress = "…",
  completed = "✓",
  failed = "✗",
  cancelled = "⊘",
}

local CHILD_STATUS_TO_STATE = {
  pending = "generating",
  in_progress = "generating",
  completed = "succeeded",
  failed = "failed",
  cancelled = "failed",
}

---Renders the body of a subagent (Task/Agent) tool call: prompt, streamed
---progress (nested tool calls and text emitted by the subagent) and result.
---@param message avante.HistoryMessage
---@param decoration string
---@param expanded boolean | nil
---@return avante.ui.Line[]
function M.subagent_to_lines(message, decoration, expanded)
  local lines = {}
  local call = message.acp_tool_call or {}
  local input = type(call.rawInput) == "table" and call.rawInput or {}
  local commentfg = Highlights.AVANTE_COMMENT_FG

  if type(input.subagent_type) == "string" and input.subagent_type ~= "" then
    table.insert(lines, Line:new({ { decoration }, { "Agent: " .. input.subagent_type, commentfg } }))
  end

  local prompt = M.get_subagent_prompt(message)
  if prompt and prompt ~= "" then
    table.insert(lines, Line:new({ { decoration }, { "Prompt:", commentfg } }))
    vim.list_extend(lines, text_to_truncated_lines(prompt, decoration, not expanded))
  end

  local children = message.acp_children or {}
  if #children > 0 then
    if #lines > 0 then table.insert(lines, Line:new({ { decoration }, { "" } })) end
    table.insert(lines, Line:new({ { decoration }, { "Progress:", commentfg } }))
    for _, child in ipairs(children) do
      if child.type == "tool_call" then
        local tc = child.tool_call or {}
        local status = tc.status or "pending"
        local icon = CHILD_STATUS_ICON[status] or "…"
        local hl = STATE_TO_HL[CHILD_STATUS_TO_STATE[status] or "generating"]
        local title = tc.title or tc.kind or "tool"
        table.insert(lines, Line:new({ { decoration }, { "├─ " }, { " " .. icon .. " " .. title .. " ", hl } }))
        if expanded and tc.content then
          vim.list_extend(lines, M.get_content_lines(tc.content, decoration .. "│   ", false))
        end
      elseif child.type == "text" or child.type == "thought" then
        local prefix = child.type == "thought" and "> " or ""
        local text_lines = vim.split(child.text or "", "\n")
        --- trim trailing empty lines
        while #text_lines > 0 and text_lines[#text_lines] == "" do
          table.remove(text_lines, #text_lines)
        end
        local start_idx = 1
        if not expanded and #text_lines > 3 then
          start_idx = #text_lines - 2
          table.insert(
            lines,
            Line:new({
              { decoration },
              { string.format("│  ... (%d earlier lines not shown)", start_idx - 1), commentfg },
            })
          )
        end
        for idx = start_idx, #text_lines do
          table.insert(lines, Line:new({ { decoration }, { "│  " .. prefix .. text_lines[idx] } }))
        end
      end
    end
  end

  if call.status == "completed" or call.status == "failed" then
    local result_text = M.get_first_text_content(call.content)
    -- the initial tool_call content is the prompt; only show content as a
    -- result if it changed (the shim replaces content with the tool result)
    if call.content and result_text ~= prompt then
      if #lines > 0 then table.insert(lines, Line:new({ { decoration }, { "" } })) end
      table.insert(lines, Line:new({ { decoration }, { call.status == "failed" and "Error:" or "Result:", commentfg } }))
      vim.list_extend(lines, M.get_content_lines(call.content, decoration, not expanded))
    end
  end

  return lines
end

---Renders the body of a plan (ExitPlanMode) tool call: the full plan
---markdown plus the approval outcome.
---@param message avante.HistoryMessage
---@param decoration string
---@return avante.ui.Line[]
function M.plan_to_lines(message, decoration)
  local lines = {}
  local call = message.acp_tool_call or {}
  local commentfg = Highlights.AVANTE_COMMENT_FG
  local plan = M.get_plan_text(message)
  if plan and plan ~= "" then
    -- Plans are meant to be read in full, so never truncate them
    vim.list_extend(lines, text_to_lines(plan, decoration))
  else
    table.insert(lines, Line:new({ { decoration }, { "(no plan content)", commentfg } }))
  end
  if call.status == "completed" then
    table.insert(lines, Line:new({ { decoration }, { "" } }))
    table.insert(lines, Line:new({ { decoration }, { "Plan approved, leaving plan mode.", commentfg } }))
  elseif call.status == "failed" then
    table.insert(lines, Line:new({ { decoration }, { "" } }))
    table.insert(lines, Line:new({ { decoration }, { "Plan rejected, still in plan mode.", commentfg } }))
  elseif message.is_calling or call.status == "pending" or call.status == "in_progress" then
    table.insert(lines, Line:new({ { decoration }, { "" } }))
    table.insert(lines, Line:new({ { decoration }, { "Waiting for approval to leave plan mode...", commentfg } }))
  end
  return lines
end

---@param message avante.HistoryMessage
---@return string tool_name
---@return string | nil error
function M.get_tool_display_name(message)
  local content = message.message.content
  if type(content) ~= "table" then return "", "expected message content to be a table" end

  ---@cast content AvanteLLMMessageContentItem[]

  if not islist(content) then return "", "expected message content to be a list" end

  local item = message.message.content[1]

  local native_tool_name = item.name
  if native_tool_name == "other" and message.acp_tool_call then
    native_tool_name = message.acp_tool_call.title or "Other"
  end
  if message.acp_tool_call and message.acp_tool_call.title then native_tool_name = message.acp_tool_call.title end
  if not message.displayed_tool_name then
    if M.is_subagent_tool_call(message) then return "Subagent: " .. native_tool_name, nil end
    if M.is_plan_tool_call(message) then return "Plan: " .. native_tool_name, nil end
  end
  local tool_name = native_tool_name
  if message.displayed_tool_name then
    tool_name = message.displayed_tool_name
  else
    local param
    if item.input and type(item.input) == "table" then
      local path
      if type(item.input.path) == "string" then path = item.input.path end
      if type(item.input.rel_path) == "string" then path = item.input.rel_path end
      if type(item.input.filepath) == "string" then path = item.input.filepath end
      if type(item.input.file_path) == "string" then path = item.input.file_path end
      if type(item.input.query) == "string" then param = item.input.query end
      if type(item.input.pattern) == "string" then param = item.input.pattern end
      if type(item.input.command) == "string" then
        param = item.input.command
        local pieces = vim.split(param, "\n")
        if #pieces > 1 then param = pieces[1] .. "..." end
      end
      if native_tool_name == "execute" and not param then
        if message.acp_tool_call and message.acp_tool_call.title then param = message.acp_tool_call.title end
      end
      if not param and path then
        local relative_path = Utils.relative_path(path)
        param = relative_path
      end
    end
    if not param and message.acp_tool_call then
      if message.acp_tool_call.locations then
        for _, location in ipairs(message.acp_tool_call.locations) do
          if location.path then
            local relative_path = Utils.relative_path(location.path)
            param = relative_path
            break
          end
        end
      end
    end
    if
      not param
      and message.acp_tool_call
      and message.acp_tool_call.rawInput
      and message.acp_tool_call.rawInput.command
    then
      param = message.acp_tool_call.rawInput.command
      pcall(function()
        local project_root = Utils.root.get()
        param = param:gsub(project_root .. "/?", "")
      end)
    end
    if param then tool_name = native_tool_name .. "(" .. vim.inspect(param) .. ")" end
  end

  ---@cast tool_name string

  return tool_name, nil
end

---Closes a tool block: adds a placeholder body when empty, strips trailing
---blank lines and draws the bottom corner on the last line.
---@param lines avante.ui.Line[]
---@param decoration string
---@param state string
---@return avante.ui.Line[]
local function finish_tool_lines(lines, decoration, state)
  if #lines <= 1 then
    if state == "generating" then
      table.insert(lines, Line:new({ { decoration }, { "...", Highlights.AVANTE_COMMENT_FG } }))
    else
      table.insert(lines, Line:new({ { decoration }, { "completed" } }))
    end
  end
  --- remove last empty lines
  while #lines > 1 and lines[#lines].sections[2] and lines[#lines].sections[2][1] == "" do
    table.remove(lines, #lines)
  end
  local last_line = lines[#lines]
  last_line.sections[1][1] = "╰─  "
  return lines
end

---Converts a tool invocation into format suitable for UI
---@param item AvanteLLMMessageContentItem
---@param message avante.HistoryMessage
---@param messages avante.HistoryMessage[]
---@param expanded boolean | nil
---@return avante.ui.Line[]
local function tool_to_lines(item, message, messages, expanded)
  -- local logs = message.tool_use_logs
  local lines = {}

  local tool_name, error = M.get_tool_display_name(message)
  if error then
    table.insert(lines, Line:new({ { "❌ " }, { error } }))
    return lines
  end

  local rest_input_text_lines = {}

  local result = Helpers.get_tool_result(item.id, messages)
  local state
  if not result then
    state = "generating"
  elseif result.is_error then
    state = "failed"
  else
    state = "succeeded"
  end
  table.insert(
    lines,
    Line:new({
      { "╭─ " },
      { " " .. tool_name .. " ", STATE_TO_HL[state] },
      { " " .. state },
    })
  )
  -- if logs then vim.list_extend(lines, tool_logs_to_lines(item.name, logs)) end
  local decoration = "│   "
  if M.is_subagent_tool_call(message) then
    vim.list_extend(lines, M.subagent_to_lines(message, decoration, expanded))
    return finish_tool_lines(lines, decoration, state)
  end
  if M.is_plan_tool_call(message) then
    vim.list_extend(lines, M.plan_to_lines(message, decoration))
    return finish_tool_lines(lines, decoration, state)
  end
  if rest_input_text_lines and #rest_input_text_lines > 0 then
    local lines_ = text_to_lines(table.concat(rest_input_text_lines, "\n"), decoration)
    local line_count = 0
    for idx, line in ipairs(lines_) do
      if not expanded and line_count > 3 then
        table.insert(
          lines,
          Line:new({
            { decoration },
            {
              string.format("... (Input truncated, remaining %d lines not shown)", #lines_ - idx + 1),
              Highlights.AVANTE_COMMENT_FG,
            },
          })
        )
        break
      end
      line_count = line_count + 1
      table.insert(lines, line)
    end
    table.insert(lines, Line:new({ { decoration }, { "" } }))
  end
  local add_diff_lines = false
  if item.input and type(item.input) == "table" then
    if type(item.input.old_str) == "string" and type(item.input.new_str) == "string" then
      local diff_lines = M.get_diff_lines(item.input.old_str, item.input.new_str, decoration, not expanded)
      add_diff_lines = true
      vim.list_extend(lines, diff_lines)
    end
  end
  if
    not add_diff_lines
    and message.acp_tool_call
    and message.acp_tool_call.rawInput
    and message.acp_tool_call.rawInput.oldString
  then
    local diff_lines = M.get_diff_lines(
      message.acp_tool_call.rawInput.oldString,
      message.acp_tool_call.rawInput.newString,
      decoration,
      not expanded
    )
    vim.list_extend(lines, diff_lines)
  end
  if
    message.acp_tool_call
    and message.acp_tool_call.rawOutput
    and message.acp_tool_call.rawOutput.metadata
    and message.acp_tool_call.rawOutput.metadata.preview
  then
    local preview = message.acp_tool_call.rawOutput.metadata.preview
    if preview then
      local content_lines = M.get_content_lines(preview, decoration, not expanded)
      vim.list_extend(lines, content_lines)
    end
  else
    if message.acp_tool_call and message.acp_tool_call.content then
      local content = message.acp_tool_call.content
      if content then
        local content_lines = M.get_content_lines(content, decoration, not expanded, message.acp_terminals)
        vim.list_extend(lines, content_lines)
      end
    else
      if result and result.content then
        local result_content = result.content
        if result_content then
          local content_lines = M.get_content_lines(result_content, decoration, not expanded)
          vim.list_extend(lines, content_lines)
        end
      end
    end
  end
  return finish_tool_lines(lines, decoration, state)
end

---Converts a message item into representation suitable for UI
---@param item AvanteLLMMessageContentItem
---@param message avante.HistoryMessage
---@param messages avante.HistoryMessage[]
---@param expanded boolean | nil
---@return avante.ui.Line[]
local function message_content_item_to_lines(item, message, messages, expanded)
  if type(item) == "string" then
    return text_to_lines(item)
  elseif type(item) == "table" then
    if item.type == "thinking" or item.type == "redacted_thinking" then
      return thinking_to_lines(item)
    elseif item.type == "text" then
      return text_to_lines(item.text)
    elseif item.type == "image" then
      return { Line:new({ { "![image](" .. item.source.media_type .. ": " .. item.source.data .. ")" } }) }
    elseif item.type == "tool_use" and item.name then
      -- ACP tool calls use ACP "kind"s as names (think, execute, ...); they are
      -- not avante native tools, so never dispatch them to llm_tools renderers
      -- (e.g. kind "think" must not be rendered by llm_tools/think.lua).
      local ok, llm_tool = false, nil
      if not message.acp_tool_call then ok, llm_tool = pcall(require, "avante.llm_tools." .. item.name) end
      if ok then
        local tool_result_message = Helpers.get_tool_result_message(item.id, messages)
        ---@cast llm_tool AvanteLLMTool
        if llm_tool.on_render then
          return llm_tool.on_render(item.input, {
            logs = message.tool_use_logs,
            state = message.state,
            store = message.tool_use_store,
            result_message = tool_result_message,
          })
        end
      end

      local lines = tool_to_lines(item, message, messages, expanded)
      if message.tool_use_log_lines then lines = vim.list_extend(lines, message.tool_use_log_lines) end
      return lines
    end
  end
  return {}
end

---Converts a message into representation suitable for UI
---@param message avante.HistoryMessage
---@param messages avante.HistoryMessage[]
---@param expanded boolean | nil
---@return avante.ui.Line[]
function M.message_to_lines(message, messages, expanded)
  if message.displayed_content then return text_to_lines(message.displayed_content) end
  local content = message.message.content
  if type(content) == "string" then return text_to_lines(content) end
  if islist(content) then
    local lines = {}
    for _, item in ipairs(content) do
      local item_lines = message_content_item_to_lines(item, message, messages, expanded)
      lines = vim.list_extend(lines, item_lines)
    end
    return lines
  end
  return {}
end

---Converts a message item into text representation
---@param item AvanteLLMMessageContentItem
---@param message avante.HistoryMessage
---@param messages avante.HistoryMessage[]
---@return string
local function message_content_item_to_text(item, message, messages)
  local lines = message_content_item_to_lines(item, message, messages)
  return vim.iter(lines):map(function(line) return tostring(line) end):join("\n")
end

---Converts a message into text representation
---@param message avante.HistoryMessage
---@param messages avante.HistoryMessage[]
---@return string
function M.message_to_text(message, messages)
  local content = message.message.content
  if type(content) == "string" then return content end
  if islist(content) then
    return vim
      .iter(content)
      :map(function(item) return message_content_item_to_text(item, message, messages) end)
      :filter(function(text) return text ~= "" end)
      :join("\n")
  end
  return ""
end

return M
